### ISSUE TITLE
Link error while using Sigar module

### ISSUE THREAD

**Issue by dukeboard** [Spirals-Team/powerapi#75]
I faced a linkage error while starting a monitoring with the Sigar module.
Apparently, the version compiled with Scala has not the same method signature that the version delivered in the package.

java.lang.UnsatisfiedLinkError: org.hyperic.sigar.ptql.SigarProcessQuery.create(Ljava/lang/String;)V
	at org.hyperic.sigar.ptql.SigarProcessQuery.create(Native Method)
	at org.hyperic.sigar.ptql.ProcessQueryFactory.getQuery(ProcessQueryFactory.java:66)

version used: release 3.3

Best regards,

ps: don't hesitate if you want more details about the stack trace.

**Comment by mcolmant** [comment]
It should work now with the release 3.4
