### ISSUE TITLE
how to configure powerapi

### ISSUE THREAD

**Issue by nourelhoudabzr** [Spirals-Team/powerapi#84]
good morning/ afternoon
I am working on a school project that requires using powerapi to estimate the energy consumption, I don't seem to quite understand how to configure the software, though, here are the entry lines from my terminal  

mint@mint ~ $ cd Documents/
mint@mint ~ /Documents $ cd powerapi-cli/
mint@mint ~ /Documents/powerapi-cli $ ./bin/powerapi
after this i dont realy now how to proceed because the configuration file (powerapi-cli/conf /powerapi.conf) is empty and i couldn't find any documentation on how to configure it myself.
PS: i got this software version from the website powerapi.org
any help is welcome.

**Comment by mcolmant** [comment]
Hello, 

Sorry for the delay ;-)

You can have some hints in the [Wiki](https://github.com/Spirals-Team/powerapi/wiki) or via our [help](https://gitter.im/Spirals-Team/powerapi) channel. 
Several useful informations have been written there.
