### ISSUE TITLE
WIKI: Please update powerapi version in "Getting started" pages

### ISSUE THREAD

**Issue by tvincent2** [Spirals-Team/powerapi#85]
Dear powerapi developpers,

While version 4.0 has been released for a while now, the documentation still mentions version 3.3 in the _Getting started_ section, namely in pages:

- https://github.com/Spirals-Team/powerapi/wiki/Getting-started-CLI (download link)
- https://github.com/Spirals-Team/powerapi/wiki/Getting-started-API (pom.xml and build.sbt examples)
- https://github.com/Spirals-Team/powerapi/wiki/Getting-started-Daemon (download link)

Pull requests cannot be submitted for wiki pages, but I can provide you patches if needed.

Thanks for your work on powerapi!

Thomas

**Comment by mcolmant** [comment]
Hello, 

Thanks for having reported this issue!
I do not have the time to update it right now, but in the next weeks.
But if you want to create the patches and to contribute, I will be happy to merge them.

Thanks,

**Comment by tvincent2** [comment]
Dear Maxime,

Please find attached a patch changing all references to version 3.3 into references to version 4.0 in the _Getting started_ pages.

Thomas

[update_version_in_getting_started_pages.txt](https://github.com/Spirals-Team/powerapi/files/861740/update_version_in_getting_started_pages.txt)

**Comment by mcolmant** [comment]
Hello,

The patch has been merged, thanks for your contribution!
We still have to work on the Wiki to get a complete description of what we can do with PowerAPI.

Maxime.
