### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by tvincent2** [Spirals-Team/powerapi#87]
Dear PowerAPI maintainers,

A new version 4.0 of PowerAPI has been released in April, which overrides the previous version 4.0 released about a year before.

However, the behaviour between the two versions is different and the new release contains files mentioning a v4.2 (namely _lib/powerapi-cli.powerapi-cli-4.2.jar_).

Would it be possible to clear the situation by separating versions 4.0 and 4.2?

Thanks a lot for your work on PowerAPI,
Thomas

**Comment by rouvoy** [comment]
There seems to be a conflict in the numbering of versions indeed. We will investigate this issue asap and fix the release. Meanwhile, you can compile the latest version from the repository or use the Docker container made available on DockerHub.

**Comment by tvincent2** [comment]
Hello,

Little follow up. Do you have news about this issue?

Thanks a lot for your work on PowerAPI,
Thomas

**Comment by gfieni** [comment]
Hello,
I rebuilt the 4.0 release with 14/04/2016 sources and released the 4.2 with the current master tree.
The 4.0 release should have the expected behavior, can you confirm ?

Thanks

**Comment by tvincent2** [comment]
Hello,

I confirm that the 4.0 release has indeed the expected behaviour.
Thanks a lot for this fix!

Thomas
