### ISSUE TITLE
Getting 0 mhz - Core i7-4700MQ Hasswell

### ISSUE THREAD

**Issue by ranidentity** [Spirals-Team/powerapi#88]
Hi Guys,

I am having a problem to get a reading, i tried with " procfs-cpu-simple monitor --frequency 1000 --pids xxx" (valid pids)
but somehow i only get 0 mhz, it keep on spaming 0 mhz...
i have checked my tdp (google) and then set in the configuration (as below)
![image](https://user-images.githubusercontent.com/21158311/32982901-a2e48b3e-ccc6-11e7-875e-3548cfbdb175.png)
I wonder is there anything else that i need to do or miss out?

Thanks.

**Comment by mcolmant** [comment]
Hi,

Thanks for using PowerAPI.

The `procfs-cpu-simple` is reserved to Unix systems.
As you're on Windows, you may use the `sigar-cpu-simple` module instead.

I hope it will help you.

**Comment by ranidentity** [comment]
Hi,
I tried "sigar-cpu-simple monitor --frequency 1000 --pids 4140" 
but it return unknown cli option for sigar-cpu-simple.

**Comment by mcolmant** [comment]
How do you launch the binary?
I have the feeling it's because we have to launch the binary from the main folder of powerapi, not directly inside the bin folder.

**Comment by ranidentity** [comment]
Hi,

previously i do it from the bin folder.

And i tried to run it at main folder of powerapi but it shows this
![image](https://user-images.githubusercontent.com/21158311/33231017-c922e068-d228-11e7-8322-aa7d9d08d3b8.png)

Thanks for the quick reply !

**Comment by mcolmant** [comment]
Hi,

Did you try from the main folder PowerAPI?
```
powerapi-cli\powerapi modules ...
```
