### ISSUE TITLE
Unable to configure powerApi in ubuntu 14.04 Help please

### ISSUE THREAD

**Issue by jkamga** [Spirals-Team/powerapi#96]

**Comment by jkamga** [comment]
Bonjour,

Je me prenomme Justin. Je travaille depuis deux semaine a faire fonctionner PowerAPI (https://github.com/Spirals-Team/powerapi) sous ubuntu avec l'IDE intellj. Jusqu'ici j'y suis pas parvenu. je pense que la documentation est moins simple que j'aurai cru. pouvez-vous m'aider svp^

Merci

**Comment by jkamga** [comment]
jkamga@jkamga-Lenovo-Ideapad-Flex-15:~/IdeaProjects/powerapi/powerapi-daemon$ sudo ./bin/powerapid start
[sudo] Mot de passe de jkamga : 
sudo: ./bin/powerapid : commande introuvable

**Comment by rouvoy** [comment]
Given the provided message, the requested command is not located in the expected directory.

**Comment by jkamga** [comment]
that's right. but my question is what are the steps to get there please? I have troubles to make it run locally

**Comment by rouvoy** [comment]
Actually, there was no question in your issue...

Did you added the configuration files as [mentioned here](https://github.com/Spirals-Team/powerapi/wiki/Getting-started-Daemon) after unzipping the archive?

**Comment by jkamga** [comment]
Firstly the download link result in 404 not found. I cloned this https://github.com/Spirals-Team/powerapi.git from github.

**Comment by rouvoy** [comment]
Did you try to download one of the [latest release](https://github.com/Spirals-Team/powerapi/releases)?

**Comment by jkamga** [comment]
Soory for being late. I downloaded this version powerapi-cli-4.2.1.tgz and unzipped it but my trouble now is how to cinfigure it. Can you please help for that? thanks.

**Comment by jkamga** [comment]
installed
